### ISSUE TITLE
一个使用中的问题

### ISSUE THREAD

**Issue by MugWorld** [sososeen09/MultiTypeJsonParser#1]
TargetUpperLevelDeserializer这个类中的这几行要不要注释掉?返回null的话,该类的其他字段都没有数据了,我这边是这样的.
 // 未注册的类型直接返回null
//                if (!checkHasRegistered(typeValue)) {
//                    return null;
//                }

**Comment by sososeen09** [comment]
设计的初衷是随着版本的升级，后端返回的type类型可能会增加，而老版本中没有注册这个type，如果返回Bean不为null，其实这个数据就只是解析到它的父类，当你在使用的时候如果强转为子类是会报错的。
